Microsoft Windows [Version 10.0.22000.978]
(c) Microsoft Corporation. All rights reserved.

C:\Users\soraq\OneDrive\Desktop\Codingdojo\python_stack\django\django_fundamentals\Users>call C:\Users\soraq\OneDrive\Desktop\Codingdojo\python_stack\djangoPy3Env\Scripts\activate

(djangoPy3Env) C:\Users\soraq\OneDrive\Desktop\Codingdojo\python_stack\django\django_fundamentals\Users>python manage.py makemigrations
No changes detected

(djangoPy3Env) C:\Users\soraq\OneDrive\Desktop\Codingdojo\python_stack\django\django_fundamentals\Users>python manage.py shell
Python 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from my_app.models import *
>>> Users.objects.create(first_name='Amin',last_name='Al3sal',email_address='amin@axsos',age=23)
<Users: Users object (5)>
>>> c=User.objects.get(id=4)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'User' is not defined
>>> c=Users.objects.get(id=4)
>>> c.delete()
(1, {'my_app.Users': 1})
>>> c=Users.objects.get(id=3)
>>> c.delete()
(1, {'my_app.Users': 1})
>>> c=Users.objects.get(id=2)
>>> c.delete()
(1, {'my_app.Users': 1})
>>> Users.objects.create(first_name='Sura',last_name='Qalalwa',email_address='sura@axsos',age=26)
<Users: Users object (6)>
>>> Users.objects.create(first_name='Akram',last_name='Qalalwa',email_address='sura@axsos',age=28)
<Users: Users object (7)>
>>> c = Users.objects.get(id=5)
>>> c = Users.objects.first()
>>> Users.objects.all()
<QuerySet [<Users: Users object (5)>, <Users: Users object (6)>, <Users: Users object (7)>]>
>>> Users.objects.first()
<Users: Users object (5)>
>>> Users.objects.last()
<Users: Users object (7)>
>>> c = Users.objects.get(id=3)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\soraq\OneDrive\Desktop\Codingdojo\python_stack\djangoPy3Env\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\soraq\OneDrive\Desktop\Codingdojo\python_stack\djangoPy3Env\lib\site-packages\django\db\models\query.py", line 406, in get
    raise self.model.DoesNotExist(
my_app.models.Users.DoesNotExist: Users matching query does not exist.
>>> c = Users.objects.get(id=5)
>>> c.last_name = "pancakes"
>>> c.save()
>>> c = Users.objects.get(id=6)
>>> c.delete()
(1, {'my_app.Users': 1})
>>> Users.objects.all().values()
<QuerySet [{'id': 5, 'first_name': 'Amin', 'last_name': 'pancakes', 'email_address': 'amin@axsos', 'age': 23, 'created_at': datetime.datetime(2022, 9, 24, 7, 32, 52, 368962, tzinfo=<UTC>), 'updated_at': datetime.datetime(2022, 9, 24, 7, 45, 38, 880653, tzinfo=<UTC>)}, {'id': 7, 'first_name': 'Akram', 'last_name': 'Qalalwa', 'email_address': 'sura@axsos', 'age': 28, 'created_at': datetime.datetime(2022, 9, 24, 7, 38, 36, 967802, tzinfo=<UTC>), 'updated_at': datetime.datetime(2022, 9, 24, 7, 38, 36, 967802, tzinfo=<UTC>)}]>
>>> Users.objects.all().order_by("first_name")
<QuerySet [<Users: Users object (7)>, <Users: Users object (5)>]>
